export const DASHBOARD_DRAWER_TOGGLE = 'DASHBOARD_DRAWER_TOGGLE';
export const DASHBOARD_DRAWER_CLOSE = 'DASHBOARD_DRAWER_CLOSE';

export const PLAYER_MOUNT = 'PLAYER_MOUNT';
export const PLAYER_UPDATE = 'PLAYER_UPDATE';
export const PLAYER_COMMAND = 'PLAYER_COMMAND';